<?php
/**
 * Facebook - Installation routines.
 */

/**
 * Remove all things associated with the module.
 *
 * @seealso hook_uninstall()
 */
function facebook_uninstall() {
    // Facebook application settings
    variable_del('facebook_app_id');
    variable_del('facebook_app_secret');
    variable_del('facebook_app_access_token');
    // Facebook page settings
    variable_del('facebook_page');
}